// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go

// Package mock_get_other_user_profile is a generated GoMock package.
package mock_get_other_user_profile

import (
	model "aggregationframework/internal/model/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetOtherUserProfile mocks base method.
func (m *MockService) GetOtherUserProfile(username, currentUsername string) (*model.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOtherUserProfile", username, currentUsername)
	ret0, _ := ret[0].(*model.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOtherUserProfile indicates an expected call of GetOtherUserProfile.
func (mr *MockServiceMockRecorder) GetOtherUserProfile(username, currentUsername interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOtherUserProfile", reflect.TypeOf((*MockService)(nil).GetOtherUserProfile), username, currentUsername)
}
