// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_get_other_user_profile is a generated GoMock package.
package mock_get_other_user_profile

import (
	model "aggregationframework/internal/model/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockfollowConnector is a mock of followConnector interface.
type MockfollowConnector struct {
	ctrl     *gomock.Controller
	recorder *MockfollowConnectorMockRecorder
}

// MockfollowConnectorMockRecorder is the mock recorder for MockfollowConnector.
type MockfollowConnectorMockRecorder struct {
	mock *MockfollowConnector
}

// NewMockfollowConnector creates a new mock instance.
func NewMockfollowConnector(ctrl *gomock.Controller) *MockfollowConnector {
	mock := &MockfollowConnector{ctrl: ctrl}
	mock.recorder = &MockfollowConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfollowConnector) EXPECT() *MockfollowConnectorMockRecorder {
	return m.recorder
}

// CheckIfRelationshipExists mocks base method.
func (m *MockfollowConnector) CheckIfRelationshipExists(followeeId, followerId string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfRelationshipExists", followeeId, followerId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIfRelationshipExists indicates an expected call of CheckIfRelationshipExists.
func (mr *MockfollowConnectorMockRecorder) CheckIfRelationshipExists(followeeId, followerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfRelationshipExists", reflect.TypeOf((*MockfollowConnector)(nil).CheckIfRelationshipExists), followeeId, followerId)
}

// MockreadmodelsConnector is a mock of readmodelsConnector interface.
type MockreadmodelsConnector struct {
	ctrl     *gomock.Controller
	recorder *MockreadmodelsConnectorMockRecorder
}

// MockreadmodelsConnectorMockRecorder is the mock recorder for MockreadmodelsConnector.
type MockreadmodelsConnectorMockRecorder struct {
	mock *MockreadmodelsConnector
}

// NewMockreadmodelsConnector creates a new mock instance.
func NewMockreadmodelsConnector(ctrl *gomock.Controller) *MockreadmodelsConnector {
	mock := &MockreadmodelsConnector{ctrl: ctrl}
	mock.recorder = &MockreadmodelsConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreadmodelsConnector) EXPECT() *MockreadmodelsConnectorMockRecorder {
	return m.recorder
}

// GetUserProfile mocks base method.
func (m *MockreadmodelsConnector) GetUserProfile(username string) (*model.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfile", username)
	ret0, _ := ret[0].(*model.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfile indicates an expected call of GetUserProfile.
func (mr *MockreadmodelsConnectorMockRecorder) GetUserProfile(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfile", reflect.TypeOf((*MockreadmodelsConnector)(nil).GetUserProfile), username)
}
