// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_get_other_user_profile is a generated GoMock package.
package mock_get_other_user_profile

import (
	model "aggregationframework/internal/model/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetOtherUserProfile mocks base method.
func (m *MockRepository) GetOtherUserProfile(username, currentUsername string) (*model.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOtherUserProfile", username, currentUsername)
	ret0, _ := ret[0].(*model.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOtherUserProfile indicates an expected call of GetOtherUserProfile.
func (mr *MockRepositoryMockRecorder) GetOtherUserProfile(username, currentUsername interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOtherUserProfile", reflect.TypeOf((*MockRepository)(nil).GetOtherUserProfile), username, currentUsername)
}
